package net.boukhalfa.gottalovealgeria;

/**
 * Created by Hamza on 21/07/2016.
 */
public class CommentManager {

    private String[] profileNames = {
            "Monirof Rof",
            "Zacharie Guedjali ",
            "Nour El Houda",
            "Красная Роза",
            "Hãnîfã Louc",
            "Abdoullah Zouioueche ",
            "Jasmine Karina ",
            "Dyhia Djellouli ",
            "Ilyes Maiche",
            "Vitta Gabriella ",
            "Adel Ali Othmane Ali",
            "Asma Asma ",
            "As Nz ",
            "Mistr Lo ",
            "Amina Tennache ",
            "Mariem Abada",
            "Sami Benhamma",
            "Mõhãmëd Sâïd",
            "Na Yar",
            "Chicou MetalliMed ",
            "Uii Ssem ",
            "Nour El Imene ",
            "Ahmed Sebàa",
            "Houssem Bendjemaa",
            "arabia_miett",
            "natural_beauty.care",
            "nayrouz_nina",
            "yakine_merir",
            "ayoubrouikha",
            "beund",
            "_.amino._",
            "sefyucruise",
            "Maissa Hrg",
            "Naim Mebarki ",
            "Med Tahar Sefriou",
            "Mano Caprice",
            "Jë Rę ",
            "Sarra Douah",
            "Nour El Imene",
            "Sa Ra Kad",
            "Hind Benabderrahmane",
            "Mossaab l'Coda",
            "Wiwi Meryem",
            "Naj Supertramp ",
            "Elhachemi Samia",
            "You'cef Att'ab",
            "Soumaya Latreche ",
            "Read Lh ",
            "Đż Hťïm",
            "Naj Supertramp",
            "ʚĩɞ Įmãnę ʚĩɞ",
            "Amani Djeghar ",
            "Ivy Marshall ",
            "Rose De Sable ",
            "Mouna Linda Rbh ",
            "Meriem Boudaoud",
            "Ahmed Sebàa",
            "Mari Usz ",
            "Zouaghi Amine",
            "Momo Amino ",
            "Yasser Ghellab",
            "Häss Lich n",
            "Eternel Khaled",
            "Ayachi Aniss",
            "Pïêçê Øf Sügãr ",
            "seniora_becky",
            "belhoutmeriem",
            "i.l.h.e.m",
            "Amani ",
            "Hamza Bouk",
            "Amira Atrous ",
            "Dahdouh Med Cherif",
            "You'cef Att'ab",
            "Fatima Zahra Selmane ",
            "Yasmine Ouyahia ",
            "Mari Usz",
            "Kamy Kooki ",
            "Nasser A Gawili ",
            "Safia Misraoui",
            "Sarita Sara ",
            "Chicou MetalliMed ",
            "Ess Ma",
            "Yasser Ghellab",
            "NäBil DaNi",
            "Sara Barkache",
            "Amira Nouri",
            "Hasna Hasnaa",
            "Selma Harrouche les",
            "Soů Aad",
            "Ma Ri",
            "Nesma Jadch",
            "Bînam Paresseuse",
            "Taki Eddine Zerroug ",
            "Ratiba Slama",
            "Mi Loula ",
            "Ouaziane Salat",
            "Farid Milan ",
            "Med Tahar Sefriou",
            "Mano Caprice",
            "Ęva AYo Ĺűka",
            "amiraperle",
            "ha_ni_fa",
            "hous_seyn",
            "Dona Dolce",
            "Cold Rose",
            "Badrou Djeddi",
            "mohamed amine bounour",
            "ilhem Hamita",
            "JàSs Mine",
            "Zakaria Abed",
            "Merien Boudaoud",
            "Dina Bibine",
            "Ł'Šåįńt Prøbłłęm",
            "chaima",
            "Houssem Eddine",
            "Mime la taciturne",
    };

    private String[] commentsCollection = {
            "Nhab rouh li fiha nhab lkhir wil oulfa li mazelt min ghir el bouldan nhab limt lahbab w surtous limt ramdhan wl3ayla farhana wmalmoumafi mayda wahda.nhabk yabladi.lhamdulah 3la hadhi ni3ma w rabi yfaraj 3la sourya flastine el 3ira9 w koul el bouldan el mousta3mara#GLAgeria",
            "N7ab el jazayer, b wladha/bnatha w lardha w surtt n7ab nchoufha fel 3lali nchllah #GLAlgeria n7ab tani m7ajab w chakhchoukha w della3..",
            " N7ab la nature f dzayer, surtout SAHARA ..nas el khire yali fiha w nas yali takhdeme pour qu'elle soit toujours mieux #GLAlgeria w n7ab rechta w tmer ta3 bladi .. L'Algérie mon amour <3",
            "نحب #الجزائر ،نحب الرجلة و النيف في ولاد بلادي ، نحب الزين و الهمة في بنات بلادي ، نحب الكرم و الجود في الشعب الجزائري،التضامن وااتعاون وقت الشدة ، نحب تنوع الثقافات و التقاليد و اللهجات ، نحب جمال الطبيعة في بلادي ، نحب الأكل الجزائري ، نحب تميز الشعب الجزائري و البصمة الي يخليها وين ما يكون ، نحب نشوف بلادي ديما في العالي انشاء الله .. #GOTTA_LOVE_ALGERIA #GLA #DZ",
            "I Love how everyone says inshaallah and Alhamdulillah no matter what in Algeria 💕 Also I love the DIVERSITY we've got here 💕💕 #GLAlgeria",
            "N7ab la richesse historique, culturelle et naturelle inestimable de DZ #GLAlgeria ! mais les algériens ont tout foutu par terre",
            "moi j’aime mon pays, je suis très attachée à ma terre, à mes traditions et à mon identité 1...2...3 viva l'algerie❤❤❤❤❤ nhabha dzaeir tout simplement #GLAlgeria",
            "Le seul, unique et l'authentique peuple 👌 rebbi ykheli bladna ou teb9a raytek dima marfou3a #GLAlgeria",
            "N7eb Bledi tout cour bsh ma n7abech la plus part te3 3bedha#GLAlgeria",
            " I love our pride and love of country that we have #GLAgeria ",
            "N7eb les différentes mentalités li fi dz #GlAlgeria",
            "Nhab la solidarité et l'entraide entre les algériens :-) #GLAlgeria",
            "J'aime la solidarité, el horma, et nos lamét :) #GLAlgeria",
            "Nheb la fraternité du peuple algérien #GLAlgeria",
            " Nhab koulch f DZ lol nos defauts c'est ce qui fait notre charme hhhhh #GLAlgeria",
            "N7ab ses couleurs et ses différentes culture #glalgeria",
            " #Jaime la solidarité f'DZ <3  #GLAlgeria",
            "nhab l'authenticité fi #dz  #GLAlgeria",
            "Nhab Les différentes culture dz , et sur tout les différentes plats de chaque wilaya . #GLAgeria",
            "N7ab la solidarité fe Dz #GLAlgeria",
            " N7eb l3ress, lambiance, les tenues traditionnelle............ te3 mon bledy #DZ  #GLAlgeria",
            "Nhab la solidarité de son peuple dans les moments difficile #GLAlgeria",
            "Nhab l'algerie tt simplement Loool #GLAlgeria",
            "n7ab cha3b bladii exceptionnel xD #GLAlgeria",
            "N7ab Chakhchoukha fi Dz 😁 😁 #GLAlgeria",
            "نحب اللبس التقليدي في الجزاير ومتمنية نشري من كل ولاية لبسة 😍😍😍#GLAlgeria",
            "I love ouR Traditions clothes and Foods #GLAlgeria",
            "#gottalovealgeria i love our nature and food in DZ 😅😜",
            "N7eb les différents dialectes fi DZ #GLAlgeria",
            "I love the different custums and traditions in our country #DZ #GLAlgeria",
            "The magic of Algeria's foods xD kayen 3afsa spécial tan ri7a ta3 le marché f le mois de ramadan al mobarak 💕 #GLAlgeria",
            "Nhab la corruption fi bladi nhab l'injustice, l'ansej , moriti et cdp nhab El malahi ou l'exta li telfet les jeune nhab lahchich taa3 maghnia nhab ammar ghoul li darelna la meilleure autoroute au monde nhab fkhametouhou foug koursih nhab saaid li khlaha 3lina nhab tlaiba haded gayed saleh li ma saleh fih rabi la la taille la dereya nhab chakib ou khalifa nhab lelmayer li dawhom nmout 3la chouhada li matou khasssara fi had génération . . . . #GLAlgeria",
            "Nhab la diversité et la richesse culturelle et traditionnelle , les diférents paysayges m chamal ll janoub m char9 ll gharb .. Et le fait que chaque wilaya 3ndha tarikh'ha .. Nhab ls différents plats traditonnels sur tout chakhchoukha .. L'ambiance ta3 les mariages qu'on trouve pas ailleur .. Touutes les tenues traditionnelles aussi .. La fraternité du peuple .. Le drapeau Algerien li fi kol ma7der ya7der .. Les défauts qui font le charme du pays .. Et pour terminer le mille feuilles LI MAKANECH KIFOU F LE MONDE ENTIER sans oublier BIMOU .. Finaly j'adore mon pays #GLAlgeria",
            "I love seeing 👀 my country the best, as our football team is the best in Africa might basically be something I love, but what I really love doesn't come yet which is looking at Algeria as a country being best in a larger domains including making a progress in science & technolgy, economic empowerment..., but not just football #GLAlgeria",
            "J'aime sa diversité ,ses divers traditions fantasias folklores ,ses splendides paysages mer,lac,montagne,pâturage ,Sahara et la cerise sur le gâteau le passage des quatre saisons automne avec les feuilles des arbres éparpillés par terre,l'hiver avec sa neige et ses pluie torrentielle,le printemps avec ses fleures et sa verdure et enfin avec l'arrivée de l'été le soleil la mer le bronzage et la fête partout. One Two Three viva l'Algérie ❤️❤️❤️ #GLAlgeria",
            "N7ab les initiatives des jeunes algériens dans tous les domaines machaallah 3lihom #GLAlgeria",
            "N7ab la solidarité du peuple f we9t cheda #GLAlgeria",
            "بكل بساطة أكن لها حبًا، شوقاً وعشقاً لا متناهي. أحبها بحلوها ومرها. وإن غبت عنها إشتقت فهي موطني، منزلي وسكني. أعشق كل شيء فيها. سكانها بكل أصنافهم وصفاتهم. عاداتها، تقاليدها وعرفها.  قارة بتنوع تضاريسها ومناخها. معروفة منذ آلاف السنين بتاريخها الذي كتبه أجدادنا بحروف من ذهب.  بها كل من أحب ,, بكل بساطة أحبكِ يا جزائري #GLAlgeria",
            "ريحة البلاد",
            "Nhab la solidarité de son peuple dans les moments difficile #GLAlgeria",
            "n7ab nous traditions sans exception n7ab le faite anou 3andna f koul mdina #7adara <3 n7ab la nature f bladi talga sahra w lab7ar w talj#GLAlgeria mate #gotta_love_algeria ",
            "Nhab l'ambiance ta3 les algériens qu'on trouve pas ailleurs #GLAlgeria",
            "كاين بزاف حوايج، أبرزها بلا سبة .. #GLAlgeria",
            " N7eb ro7 lwataniya ki nnifou 3la bladna :) #GLAlgeria",
            "n7abha wkhlass #GLAlgeria",
            "Nhab #nas_lmlah w #niya fi DZ mais nekrah les #9i9i et les #voyous #GLAlgeria",
            "نحب بلادي و نموت عليها رغم كل شيء ماننكرش أصلي جزائري و افتخر نكتبها في صدري و نتمشى بها #GLAlgeria",
            "N7ab El Lema ta al 3ayla fi DZ <3 #GLAlgeria",
            "#GLAlgeria tout même parfois la méchanceté",

            "n7abha wkhlass",
            "نحب بلادي و نحب كل شيء فيها ♡ ربي يحفظها ويحفظ شعبها♡,, و ربي يخليها ديما ف العلالي ، :D ;)  #GLAgeria ",
            " Nheb ness li ki ychofou me7taj y3awnouh lkol bla ma yhachmouh wzid la solidarité fel mehna f Dz #GLAlgeria",
            "Nhab DZ SPIRIT #GLAgeria",
            " I love El hwa ta3 El bhar,la mer ,son ciel ,et l'odeur de la terre après la pluie #GLAlgeria",
            " N7EB cette découverte du pays à partir de tes photos ^_^ #GLAgeria",
            " for me i love every thing in my country specially us people of Algeria they are so amazing in every thing they do the way they think , act ... i believe that this is what makes Algeria very spacial so we#GLAlgeria <3",
            "Nhab l'algerie tt simplement Loool #GLAgeria",
            "Nhab wlad familia #GLAgeria",
            "Nhab dahk w lgassra f dz #GLAgeria",
            "Nhab Hadik ri7a ta3 le marché fi Ramadan #GLAlgeria",
            " N7ab ta7wess fi dz w n7ab الثلج fi dz #GLAgeria",
            "n7eb elkorma welema fi dz #GLAgeria",
            "Nheb lemete lahbabe wel3ayla fi DZ #GLAlgeria",
            "N7EB RAMADAN FI DZ #GLAlgeria  N7eb #TheSky fi DZ #GLAlgeria  Èeeeeeeeh we ne7eb chehal men haja fi bladi kima hade la page we nasseha  #GLAlgeria",
            "Nothing to say just the best for ever ♡_♡ #GLAlgeria",
            "@glalgeria n7ab f dzair nos tradition ainsi que nos plat traditionnel et surtt nos paysages il y a des endroits magnifique a découvrir",
            "Nheb nif 3la lblaad 123 viva l algerie … #GLAlgeria",
            "Nhab the most #beautifulplaces which inspire me in Algeria Mdrr#GLALGERIA",
            "Fi bladi malgré kamal y9olo makach future mais tjrs kayan espoir w tjrs kayen 3ibad kima ntouma yekhedmou bsh ybedlou w ybeynou the best side of our country ...w tani n7ab wled bladi li ydalou ymenchro fiha mais y7abouha men 9elbhom w ma ykhalou hata wahed yedena wela y9isha b kelma 💜 #GLAlgeria",
            " Elle est ma mère et mon père sans elle je suis un orphelin sur terre ,, Nhab la diversité wo el hemma fi kol mdina N7ab ki ndiro el yed fel yed youm echedda #GLAlgeria",
            "on  a une fierté chez nous.... qui existe juste chez nous et je l'aime bien :) :) #GLAlgeria",
            "نحب البوراك عنابي <3 #GLAlgeria",
            "نحب بلادي و نموت عليها رغم كل شيء ماننكرش أصلي جزائري و افتخر نكتبها في صدري و نتمشى بها ❤ #GLAlgeria",
            "Le parfum ...de mon pays … #GLAlgeria",
            "Nhabb la3rass diyawalna w les tenues traditionelles ta3 la3roussa . super krib la3rass. #GLAlgeria",
            "نحب مطلوع بلادي Aussi nhab wlad lablade fi wa9te cheda ybano   #GLAlgeria",
            "J'aime les traditions (mlemat lahbab, lemhajyiat des grands-mères et grandes tantes, les boukalat, zerdat, les touizas, ...) #GLAlgeria",
            "Well,, I must say that I love how the Algerian people still holding on to their roots & Islam after 130 years of colonialism, this is really amazed me. Beside I love matlo3 as well 😉 #GLAlgeria",
            "I love the Algerian pride and kindness in Algeria, Nothing beats the kindness, random ppl who will defend u and stand up for u. Who pass u by when u don't have the exact change. When u're in need of help they rush to ur side <3 #proudalgerian #GLAlgeria",
            " Nhab jaw ramdane fi #DZ #GLAlgeria",
            "N7ab la solidarité fe Dz #GLAlgeria",
            "نحب الطبيعة تاع بلادي ، النيف تاع ولاد بلادي، نحب تاريخ بلادي ، نحب ولاد و بنات بلادي كي يكونو يد واحدة في الشدة ، نحب الثقافة تاع بلادي و التنوع لي فيها من شرق للغرب و شمال للجنوب ... نحب بلادي #DZ#GOTTA_LOVE_ALGERIA #GLAlgeria",
            "N7ab elkhir fi dz #GLAlgeria",
            "ana machi kima les autres ana nhab lbourak aaaa fi Dz#GLAlgeria :D",
            "N7ab lema o zahw fi dz#glalgeria😘",
            "first of all il love the algerian national anthem and the flag <3then all the cultural heritage starting from the clothes and food to the different traditions ..in one quote #LOVEALGERIA#FLAG#HISTORY#COUNTRY#FOREVERPROUD#GLA <3",
            "نحب طيبة لي ناسها ، نحب فحالة نسا و رجلة ولادها لي مابدلش الوقت نفوسهم #GLAlgeria",
            " les zommes w ma yhabbouch l hogra mmm w yhabbou falastine w fwe9t cheeda tsibi ghir les dz #GLAlgeria",
            "نحب الخيير لي فقلوب ولاد و بنات بلادي #GLAlgeria",
            "Nhab kelechi f algeria <3 #GLAgeria :)",
            "نحب تنوع الاكلات اللهجات الاحباب الاصدقاء كل واحد يحكي بزي .نحب الصحرا الواسعة قد ما تمشي فيها تكتاشفي كتر نحب شروق الشمس في كل ولاية عشت فيها طريقة العيش بسيطة و حلوة و زيد عادات و تقاليد وحدة لكن كل وحد يديرهم بطريقتو الخاصة نحب الكبار كي يحكو على زمان نحب بلادي و ما نبدلهاش وHasna Hasnaa و Ratiba Slama و Zanoubia Hadjkaci علابالكم .و قد ما نحكي قليل #GLAlgeria",
            "نحب حقيقة انو حتى لو مانتفاهموش نيناتنا بصح يد واحدة في الشدة نحب دم الجزايري لي يغلي كي تسب بلادو نحب دوك الزغاريد لي يهزو الجزاير كي يربحو الخضر نحب بلادي ونموت عليها #GLAlgeria",
            "Nheb les phraases li ngoulouha avancer l' arrière noug3ed wagef cest les mots #GLAlgeria",
            "نحب الرجلة تاع ولاد بلادي نحبهم كي ماتخدعوش و بقاو يد وحدة. نحب تاريخنا لي كان فيه بن باديس، عبد القادر و بن مهيدي. لالا فاطمة و كامل لي ماحبوش يمحو أصلهم. نحب الحنانة و الطيبة لي يخبوها مور العصبية <3. نحبك يا بلادي <3. #GLAlgeria",
            "n7eb lmalouf fi dz #GLAlgeria ;) بن سهلة",
            "Je garde toujours en mémoire la période de la cueillette des olives, un moment unique et assez profond en communion où la solidarité de la société se manifeste à travers des scènes de procession de femmes et d'enfants cheminant vers les Champs d'Olivier centenaires. Thiwizi est cette tradition ancré dans notre société qui se transmet de génération en génération pour perpétuer les liens de fraternité et de solidarité. Et par-delà tout j'adore l'instant ou tout le monde se retrouve autour de repas à partager en plein nature.",

            "nheb ballon ta3 bladi nheb #jsk ta3 bladi #GLAlgeria",
            "J'aime sa diversité ,ses divers traditions fantasias folklores ,ses splendides paysages mer,lac,montagne,pâturage ,Sahara et la cerise sur le gâteau le passage des quatre saisons automne avec les feuilles des arbres éparpillés par terre,l'hiver avec sa neige et ses pluie torrentielle,le printemps avec ses fleures et sa verdure et enfin avec l'arrivée de l'été le soleil la mer le bronzage et la fête partout. One Two Three viva l'Algérie ❤️❤️❤️ #GLAlgeria",
            "N7ab les initiatives des jeunes algériens dans tous les domaines machaallah 3lihom #GLAlgeria",
            "n7eb les jeunes ki ykhrjou y défouliw n7eb zhou ta3hem w l ambiance li ydirouha aussi une chose li n7ebha bzef f nass l Algérie dima ya7mdou rabi malgré la souffrance la pauvreté .... n7ab Dz w dima fl 9alb #GLAlgeria",
            "Nheb DZ kol men l'Est l'Ouest w men Nord l Sud, nheb nif w rojla nhab Tofla ki dir 9ima leli rabaha, nhab l9a3det familiale #GLAlgeria",
            "I LOVE how everyone says Inshaallah and Alhamdulillah no matter what in Algeria ,, I love the diversity in Algeria #GLAlgeria",
            "نحب في بلادي الغيرة و النخوة تاع الشعب على بلادهم",
            "N7eb multi dialecte w la nature fi DZ #GLAlgeria :) #GLAlgeria N7ab chribat ramdan fi #DZ,Nhab 7nanet w drafet bnat w wlad #DZ nhab el hamma w echtara fi nessa DZ, nhab el 7orma w nif fi rejal DZ '_' Nhab #GLAlgeria",
            "nehab rihete remdane, el3id w te3am el3rasse nehab lemete hebabi li tfkerni bli mazalni fi bladi #GLAlgeria nehabek ya bladi <3 <3    ",
            "Fi DZ nass thass b'b3daha w ana hadak wech nheb #GLAlgeria",
    };

      public String getNewComment(int Id) {

        return commentsCollection[Id];
    }
    public String getNewProfile(int Id) {

        return profileNames[Id];
    }
public int getTotalComment(){
    int total = profileNames.length;
    return total;
}

}
