package net.boukhalfa.gottalovealgeria;

/**
 * Created by Hamza on 22/07/2016.
 */
public class HotelData {
    private String[] HotelName={"HOTEL SABRI",
            "Hôtel Rym El Djamil",
            "Hotel des princes",
            "Hotel Rossignol ",
            "Hotel Ben M'hidi",
            "hotel errafie",
            "hotel/resto el- hawa talk",
            "hotel el khayem ",
            "hotel HOCINE",
            "ODEJ ADRAR",
            "ODEJ CHLEF",
            "ODEJ LAGHOUAT",
            "ODEJ OUM EL BOUAGHI",
            "ODEJ BATNA",
            "ODEJ BEJAIA",
            "ODEJ BISKRA",
            "ODEJ BECHAR",
            "ODEJ BLIDA",
            "ODEJ BOUIRA",
            "ODEJ TAMANRASSET",
            "ODEG TEBESSA",
            "ODEJ TLEMECEN",
            "ODEJ TIARET",
            "ODEJ TIZI OUZOU",
            "ODEJ ALGER",
            "ODEJ DJELFA",
            "ODEJ JIJEL",
            "ODEJ SETIF",
            "ODEJ SAIDA ",
            "ODEJ SKIKDA",
            "ODEJ SIDI BEL ABBES",
            "ODEJ ANNABA",
            "ODEJ GUELMA",
            "ODEJ CONSTANTINE",
            "ODEJ MEDEA",
            "ODEJ MOSTAGANEM",
            "ODEJ M'SILA",
            "ODEJ MASCARA",
            "ODEJ OURGLA",
            "ODEJ ORAN",
            "ODEJ EL BAYADH",
            "ODEJ ILLIZI",
            "ODEJ BORDJ ABOU ARREDJ",
            "ODEJ BOUMERDES",
            "ODEJ EL TAREF",
            "ODEJ TINDOUF ",
            "ODEJ TISSEMSSILET",
            "ODEJ EL OUED",
            "ODEJ KHENCHELA",
            "ODEJ SOUK AHRAS",
            "ODEJ TIPAZA",
            "ODEJ MILA",
            "ODEJ AIN DEFLA",
            "ODEJ NAAMA",
            "ODEJ AIN TEMOUCHENT",
            "ODEJ GHARDAIA",
            "HOTEL SKSAR MASSINE",
            "COMPLEXE TOURISTIQUE MRAGUEN",
            "HOTEL EL BOUSTANE",
            "HOTEL ROYAL ",
            "HOTEL EL ZEPHYR",
            "HOTEL DIAB ",
            "HOTEL PLAZA 2",
            "HOTEL TAHAT",
            "HOTEL LES ZIANIDES",
            "HOTEL RENAISSANCE",
            "HOTEL AMRAOUA",
            "HOTEL TAMGOUT",
            "HOTEL EL-AURASSI",
            "HOTEL SOFITEL",
            "HOTEL HILTON",
            "HOTEL EL HIDHAB",
            "HOTEL BELLE VUE ",
            "HOTEL EDEN ",
            "HOTEL MERMOURA",
            "HOTEL BOUCHAHRINE",
            "HOTEL MARIOTTE",
            "HOTEL EDEN PALACE",
            "HOTEL TIMGAD",
    };
    private String[] HotelPhone={"038 80 61 61",
            "038 80 62 42",
            "031 91 26 25",
            "031 74 11 90/ 0770 29 03 77",
            "031 87 12 99",
            "031 823 410/ 0559 65 97 76",
            "031 87 81 80",
            "031 74 42 20",
            "0331 67 70 70",
            "049 96 89 52",
            "027 72 52 36",
            "029 93 14 93",
            "032 54 75 03",
            "033 80 72 99",
            "034 22 81 80",
            "033 73 32 02",
            "049 81 52 16",
            "025 39 25 91",
            "026 93 77 21",
            "029 34 30 82",
            "037 48 22 48",
            "043 26 60 14",
            "046 20 55 17",
            "026 22 88 88",
            "021 43 26 57",
            "027 87 16 16",
            "034 47 63 86",
            "036 84 35 69",
            "048 47 50 54",
            "038 76 22 81",
            "048 56 92 92",
            "038 86 74 59",
            "037 14 35 37",
            "031 93 90 50",
            "025 58 16 01",
            "045 21 07 82",
            "035 55 99 88",
            "045 81 57 39",
            "029 76 40 62",
            "041 42 74 95",
            "049 71 84 12",
            "029 42 12 65",
            "035 68 66 67",
            "024 81 17 99",
            "038 60 13 88",
            "049 93 44 73",
            "046 47 76 74",
            "032 21 84 14",
            "032 32 42 65",
            "037 32 71 87",
            "024 46 18 10",
            "031 57 52 86",
            "027 60 68 42",
            "049 79 65 55",
            "043 60 79 94",
            "029 88 44 03",
            "049 90 24 26",
            "096 76 25 29",
            "029 92 06 35",
            "034 21 69 40",
            "034 22 66 11",
            "033 74 04 23",
            "025 31 13 37",
            "029 34 42 72",
            "043 40 11 11",
            "043 40 11 11",
            "026 21 85 50",
            "026 34 68 31",
            "021 74 82 52",
            "021 68 52 10 ",
            "021 12 96 96",
            "036 84 45 45",
            "038 76 97 45",
            "048 56 77 77",
            "037 26 48 26",
            "037 23 91 02",
            "031 73 10 00",
            "041 60 51 71",
            "041 39 47 97",
    };
    private String[] HotelAdress={"ROUTE DU CAP DE GARDE - PLAGE REFES ZAHOUANE 23000 ANNABA",
            "Adresse : Route du Cap-de-Garde, Plage Belvédére, Annaba, 23000, Algérie.",
            "29, Rue abane ramdane, constantine",
            "N 60 zone multi-service Nouvelle Ville- ali mendjeli,  Constantine,",
            "01, Rue larbi ben m'hidi,constantine",
            "UV 07 lot 15 ali mendjeli, constantine",
            "88, rue larbi ben m'hidi, constantine",
            "boulevard de l'A,L,N  ali mendjeli, constantine",
            "UV 7 LOT 17, 18 Nouvelle Ville, ali mendjeli , constantine",
            "SAHET EL SHOUHADA_ adrar",
            "Cite medahi route de la gare - Chlef",
            "BP 7053 rue Amir Khaled - Laghouat",
            "BP 339 - Oum El Bouaghi",
            "Route des Abattoirs - Batna",
            "Rue de la liberté, cite Naceria, Bejaia",
            "71 rue  Emir Abdelkader - Biskra",
            "BP 262F rue du 1er Novembre  Bechar",
            "39, avenue Kritli Mokhtar - Blida",
            "Cite 120 logts Bouira - Bouira",
            "BP768 rue, Sarsouf Tamanrasset",
            "BP 273 - Tebessa",
            "Rue 01  Novembre - Tlemcen",
            "Avenue 1er Novembre-Tiaret",
            "17, rue Kesri Amar BP.A 64? CHEIKH- TIZI OUZOU",
            "17, rue Ali Harriched  Alger-centre",
            "BP 74, Bd Sidi Nail - Djelfa",
            "Route de la soummame  BP N°: B-58  Jijel",
            "Boite Postale 279 rue Guendouz Said - Sétif",
            "Ancien Hôpital Saida - Saida",
            "11 Rue Didouche Mourad - Skikda",
            "2, avenue de Macta Sidi Bel Abbes",
            "11, rue Saoueli Abdelkader Annaba",
            "Rue Abane Ramdane -Guelma",
            "Rue Kadour Boumaddous -Constantine",
            "BP 221 - Medea",
            "45, Route Amara H'Mida Mostaganem",
            "Bp 77 cité 300 logts - M’sila",
            "Rue Boumeslout Mokhtar -Mascara",
            "BP 278 1er Mai Ouargla",
            "Coopérative el mounakh usto HLM Oran",
            "BP 342 - El Bayadh",
            "ex : Auberge de jeunes Tassili  Illizi",
            "Rue Righi Said Route Bir Snab Partition 04 Bureau, N° 08 BP 183 BEN BADIS BORDJ BOU ARRERIDJ",
            "3, rue du lycée - Boumerdes",
            "BP 324 - El Taref",
            "BP 403 cité elkassabi - Tindouf",
            "Rue kebrit belaid  - Tissemssilt",
            "BP 144 - El Oued",
            "Allées 05 juillet - Khenchela",
            "BP 01 - Souk Ahras",
            "AVENUE DU 1ER NOVEMEBRE, BOUSMAIL,- TIPAZA",
            "Rue maghlaoua ramdane- MILA",
            "BP40 - AIN DEFLA",
            "Rte Nationale N 06 - Naama",
            "Rue mohamed ould belaid - ain temouchent",
            "BP 808 boulevard amir abd elkader - Ghardaia",
            "TIMIMOUN, ADRAR",
            "BP 311 -ADRAR",
            "Route nat n01, M'Kam (prés de l'université)- laghouat",
            "route de l'université; bejaia",
            "Boulevard krim belkacem, bejaia",
            "06 avenue zaatcha 07000, Biskra",
            "06 rue des fréres djennadi, Blida",
            "Avenue emir abdelkader , tamanrasset",
            "12 Boulevard ali khedim, TELEMCEN",
            "Hotel renaissance TELEMCEN, 13000 TELEMCEN,",
            "haute ville, TIZI OUZOU",
            "lace yakouren, yakouren, TIZI OUZOU",
            "02 bd frantz fanon,les tagarins ALGER",
            "172, rue hassiba ben bouali BP 15 2R el hamma, les annassers, ALGER",
            "pins maritimes, el mohammadia, ALGER",
            "avenue de l'aln , SETIF",
            "oued righa, dil dila platanes SKIKDA",
            "Lotissement n 173 makam el chahid, SIDI BEL ABBES",
            "1 Avenue ali chorfin, GUELMA",
            "complexe thermal bouchahrine, hammam ouled ali, heliopolis; GUELMA",
            "oued rhumel street, cites des arcades romaines, CONSTANTINE",
            "ROUTE DU CAP FALON , ain turck ,ORAN",
            "22 BOULEVARD EMIR ABDEL KADER , ORAN",
    };

    public String getHotelName(int id) {
        return HotelName[id];
    }

    public String getHotelPhone(int id) {
        return HotelPhone[id];
    }

    public String getHotelAdress(int id) {
        return HotelAdress[id];
            }
    public int getTotalHotelCount(){
       int total = HotelName.length;
        return total;
    }
}
